# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170905_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ctime',
            field=models.CharField(default='Thu Sep 07 2017 15:00:00 GMT+0530 (IST)', max_length=200),
        ),
    ]
