# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('content', models.CharField(max_length=5000)),
                ('views', models.IntegerField(blank=True, default=1)),
                ('posted_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
