# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short',
            field=models.CharField(default='', max_length=200),
        ),
    ]
