# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170606_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewers', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
