# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=50000),
        ),
    ]
